name: Node CI

on: [push]

jobs:
  job1:
    name: JOB ONE
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          NAME: Taro
        run: |
          echo Hello my name is $NAME.
  job2:
    name: JOB TWO
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          NAME: Hanako
        run: |
          echo Hello my name is $NAME.
  build:
    needs: [job1, job2]
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        npm install
        npm run build --if-present
